/*
*  WARNING, DO NOT EDIT: THIS IS AUTOGENERATED BY GRUNT!
*/
define("specs", [
    "test/features/ajaxError",
    "test/features/application",
    "test/features/baseFeature",
    "test/features/featureContainer",
    "test/features/viewportController",
    "test/features/VisibleFeature",
    "test/features/windowEventDispatcher",
    "test/features/column/column",
    "test/features/keymaster/keymaster",
    "test/features/navigation/navigation",
    "test/features/ranking/ranking",
    "test/features/ranking/columnDiagram/columnDiagram",
    "test/features/router/router",
    "test/features/router/notFound/notFound",
    "test/features/samples/json/json",
    "test/features/section/section",
    "test/features/socket/socket",
    "test/features/startup/startup",
    "test/features/startup/challenger/challenger",
    "test/features/startup/status/status",
    "test/features/utils/loading/loading",
    "test/features/utils/toaster/toaster",
    "test/features/welcome/welcome",
    "test/tools/eventmachine",
    "test/tools/templatestorage",
    "test/tools/urls",
    "test/collections/datas"
], function() {});
